class Main {
  public static void main(String[] args) {
    try {
      testMe();
    } catch (Exception e) {
      System.out.println("Caught " + e.getMessage() + " in main");
    }
  }

  static void testMe() throws Exception {
    try {
      throw new Exception("Original try block");
    } catch (Exception e) {
      System.out.println("Caught " + e.getMessage() + " in testMe");
      throw new Exception("Thrown in the catch block");
    } finally {
      System.out.println("In finally");
    }
  }
}